# build stage
FROM node:18 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# กำหนด API URL เป็น relative
ENV VITE_API_URL=""
RUN npm run build

# serve stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY ../default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
